# Generated by Django 4.2.14 on 2024-08-12 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistoryNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_flipkart', models.CharField(default='Not available', max_length=255)),
                ('price_amazon', models.CharField(default='Not available', max_length=255)),
                ('price_croma', models.CharField(default='Not available', max_length=255)),
                ('price_jiomart', models.CharField(default='Not available', max_length=255)),
                ('price_reliancedigital', models.CharField(default='Not available', max_length=255)),
                # ('price_vijaysales', models.CharField(default='Not available', max_length=255)),
                ('price_tatacliq', models.CharField(default='Not available', max_length=255)),
                ('price_poorvika', models.CharField(default='Not available', max_length=255)),
                ('price_shopclues', models.CharField(default='Not available', max_length=255)),
                ('price_paytmmall', models.CharField(default='Not available', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_scraper.product')),
            ],
        ),
    ]
