# Generated by Django 4.2.14 on 2024-08-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='scraped_at',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_amazon',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_croma',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_flipkart',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
