# Generated by Django 4.2.14 on 2024-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_amazon',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_croma',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_flipkart',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_jiomart',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_paytmmall',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_poorvika',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_reliancedigital',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_shopclues',
        ),
        migrations.RemoveField(
            model_name='pricehistorynew',
            name='price_tatacliq',
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='offers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='price',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='site_name',
            field=models.CharField(choices=[('flipkart', 'Flipkart'), ('amazon', 'Amazon'), ('croma', 'Croma'), ('jiomart', 'JioMart'), ('reliancedigital', 'Reliance Digital'), ('tatacliq', 'TataCliq'), ('poorvika', 'Poorvika'), ('shopclues', 'ShopClues'), ('paytmmall', 'Paytm Mall')], default='amazon', max_length=255),
        ),
        migrations.AddField(
            model_name='pricehistorynew',
            name='total_purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
