# Generated by Django 4.2.14 on 2024-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0002_remove_pricehistorynew_price_amazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistorynew',
            name='site_name',
            field=models.CharField(choices=[('flipkart', 'Flipkart'), ('amazon', 'Amazon'), ('croma', 'Croma')], default='amazon', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricehistorynew',
            name='total_purchases',
            field=models.CharField(max_length=255),
        ),
    ]
